### ISSUE TITLE
Падает при выборе папки

### ISSUE THREAD

**Issue by iHaired** [SkiTles55/SP-EFT-ProfileEditor#1]
Запускаю, указываю путь к папке server, программа вылетает. Повторно можно запустить только после удаления PEOtions.json.
Содержимое файла:
{
  "EftServerPath": "K:\\server",
  "Language": "ru",
  "DefaultProfile": null,
  "ColorScheme": "Dark.Steel"
}

**Comment by SkiTles55** [comment]
Исправлено.
