### ISSUE TITLE
Helmets

### ISSUE THREAD

**Issue by Borshig** [SkiTles55/SP-EFT-ProfileEditor#10]
**Versions | Версии**
- SPT AKI Server version | Версия SPT AKI Server -> 2.2.1
- SP-EFT-ProfileEditor version | Версия SP-EFT-ProfileEditor -> 1.9/2.0

**Describe the bug | Опишите ошибку**
A clear and concise description of what the bug is. | Четкое и краткое описание ошибки.
-> Нет категории "Шлемы" и связанных с ней предметов для добавления в схрон.
-> Missing category "Helmets" and linked objects for adding in stash.

**Additional context | Дополнительный контекст**
SPT AKI Profile file link | Ссылка на файл профиля SPT AKI

![image](https://user-images.githubusercontent.com/17796364/153751557-14050dac-17a5-4ebe-a663-f5d41459d800.png)
![image](https://user-images.githubusercontent.com/17796364/153751574-3b3dc96f-c7a3-4a0a-9756-7ad57273c069.png)
![image](https://user-images.githubusercontent.com/17796364/153751594-a4c7ca40-e93f-44a7-bfe3-3c70bd69484d.png)
![image](https://user-images.githubusercontent.com/17796364/153751600-6e723774-0163-4614-860c-1bb808bae78f.png)

**Comment by SkiTles55** [comment]
[В окне "Добавление предметов" отсутствуют некоторые предметы](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/blob/master/FAQ.md#%D0%B2-%D0%BE%D0%BA%D0%BD%D0%B5-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BE%D0%B2-%D0%BE%D1%82%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%82-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B5-%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D1%8B)
