### ISSUE TITLE
Stash - Adding Money Not Always Working

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SP-EFT-ProfileEditor#11]
I've been using this program for a few versions now.  With each version, the ONLY issue I've consistently had is with adding money from the [Stash].  Yes I have a profile created.  It NEVER adds the money the first or second time, and then after that it seems to randomly work.  I've spent hours tryin to figure out what the "pattern" is for how to get it to work, or why it is failing.  I'm at a loss.  Is there a known issue with the money not always being adding to the profile correctly?  Thanks in advance

**Comment by SkiTles55** [comment]
> I've been using this program for a few versions now. With each version, the ONLY issue I've consistently had is with adding money from the [Stash]. Yes I have a profile created. It NEVER adds the money the first or second time, and then after that it seems to randomly work. I've spent hours tryin to figure out what the "pattern" is for how to get it to work, or why it is failing. I'm at a loss. Is there a known issue with the money not always being adding to the profile correctly? Thanks in advance


If you using 2.0 version, create issue in the appropriate repository by completely filling out the bug report template.
Older versions not supported
### [Submit a bug report](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/new/choose)
