### ISSUE TITLE
Crashes On SPT-AKI A7

### ISSUE THREAD

**Issue by NazZaR** [SkiTles55/SP-EFT-ProfileEditor#2]
Crashes after I point configurator to the server folder. And does not launch after that.
https://mods.sp-tarkov.com/files/file/16-spt-aki/

**Comment by SkiTles55** [comment]
damaged or empty profile file i think. i need profile file for testing

**Comment by SkiTles55** [comment]
недостаточно данных

**Comment by NazZaR** [comment]
единственный файл в папке профиля
[1299628556.zip](https://github.com/SkiTles55/SP-EFT-ProfileEditor/files/6000280/1299628556.zip)
