### ISSUE TITLE
Проблемы с Profile Editor

### ISSUE THREAD

**Issue by WhiteLegionary** [SkiTles55/SP-EFT-ProfileEditor#4]
Здравствуйте! Пол года назад скачал SP Tarkov R7. Profile Editor 1.5 работал корректно. Пару месяцев назад он стал выдавать ошибку при запуске. Скачал 1.6 с этого сайта, проблема та же. 1.8 уже запускается, но не может найти сервер, даже если указать на него.

**Comment by SkiTles55** [comment]
Для SP Tarkov R7 подходят только версии 1.5 или 1.6. Для версии 1.8 нужно указать в файле PEOptions.json относительные пути (указаны в README), но успех не гарантируется.
Нет текста ошибки - нет помощи, но скорее всего что то не так с профилем, попробуй создать новый профиль, и редактировать его.

**Comment by k0les0** [comment]
Приветствую. Не бросайте проект) Заметил,что нет шлемов в списке добавления

**Comment by SkiTles55** [comment]
> Приветствую. Не бросайте проект) Заметил,что нет шлемов в списке добавления

Проект не заброшен, я вношу изменения при наличии времени и возможности.
Шлемы, как и некоторые другие категории предметов, отключены, так как могут повредить профиль

**Comment by k0les0** [comment]
> 
> 
> > Приветствую. Не бросайте проект) Заметил,что нет шлемов в списке добавления
> 
> Проект не заброшен, я вношу изменения при наличии времени и возможности.
> Шлемы, как и некоторые другие категории предметов, отключены, так как могут повредить профиль

Очень рад слышать!Спасибо!
