### ISSUE TITLE
Проблема с сохранением профиля

### ISSUE THREAD

**Issue by MeinFurrer** [SkiTles55/SP-EFT-ProfileEditor#5]
Когда пытаюсь сохранить профиль получаю: 
![Снимок](https://user-images.githubusercontent.com/88234590/127737992-a9931b20-ca11-44cf-8d6a-4feae7e16278.JPG)

**Comment by SkiTles55** [comment]
Версия программы? сервера? И нужен файл профиля.

**Comment by MeinFurrer** [comment]
Версия программы 1.8, сервер SPT-AKI 2.0.0-A7-BLEEDINGEDGE, 
[profile.zip](https://github.com/SkiTles55/SP-EFT-ProfileEditor/files/6912357/profile.zip)

**Comment by SkiTles55** [comment]
> Версия программы 1.8, сервер SPT-AKI 2.0.0-A7-BLEEDINGEDGE,
> [profile.zip](https://github.com/SkiTles55/SP-EFT-ProfileEditor/files/6912357/profile.zip)

SPT-AKI 2.0.0-A7-BLEEDINGEDGE не поддерживается, внимательно читайте readme
