### ISSUE TITLE
Как решить проблему с сохранением профиля?

### ISSUE THREAD

**Issue by Stilov** [SkiTles55/SP-EFT-ProfileEditor#6]
Здравствуйте, а как можно решить проблему с сохранением профиля? Я попробовал поставить старую версию SPT-AKI 1.3.0, но это мне не помогло. Всё равно выдаёт ошибку. Что я делаю неправильно. Заранее спасибо.

**Comment by SkiTles55** [comment]
@Stilov версии BLEEDING EDGE не поддерживаются. Если у вас одна из поддерживаемых версий SPT-AKI создайте сообщение об ошибке по шаблону
