### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lemniscat** [SkiTles55/SP-EFT-ProfileEditor#7]
**Versions | Версии**
- SPT AKI Server version | Версия SPT AKI Server
 BLEEDINGEDGE-2.0.0-A9
![image](https://user-images.githubusercontent.com/10240416/130494023-2705b588-5c61-4c6e-aa26-7ec2aa6b1baf.png)

- SP-EFT-ProfileEditor version | Версия SP-EFT-ProfileEditor

**Describe the bug | Опишите ошибку**
A clear and concise description of what the bug is. | Четкое и краткое описание ошибки.

23.08.2021 22:51:45: LoadDataWorker | Object reference not set to an instance of an object.

**Additional context | Дополнительный контекст**
SPT AKI Profile file link | Ссылка на файл профиля SPT AKI
[ef8acd31fd0dae5a29057975.zip](https://github.com/SkiTles55/SP-EFT-ProfileEditor/files/7033931/ef8acd31fd0dae5a29057975.zip)

**Comment by SkiTles55** [comment]
BLEEDINGEDGE не поддерживается

**Comment by lemniscat** [comment]
Так BLEEDINGEDGE  вскоре станет основной версией, когда стабильную соберут.
Развития SP-EFT-ProfileEditor больше не будет?

**Comment by SergeyBakinskiy** [comment]
BLEEDINGEDGE это серия серверов сугубо для тестирования и разработки, они не являются финальным релизом и следовательно  под BE  бессмысленно что либо писать, пока оно не обретёт окончательный(релизный вид)

**Comment by lemniscat** [comment]
Понятно что версия для тестирования.
Они на релизе очередного сервера, могут поменять модели?

**Comment by SergeyBakinskiy** [comment]
Как я уже сказал выше, в ходе работы над BE, от версии к версии частенько меняется внутренняя структура, в частности структура профиля. Под каждую версию бессмысленно что либо выпускать, пока оно не обретёт окончательный и стабильный вид.

**Comment by lemniscat** [comment]
Тогда все логично.
Предлагаю вынести пометку в readme.md  о несовместимости с BE в любых версиях
