### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by OXTHEBIG** [SkiTles55/SP-EFT-ProfileEditor#8]
**Versions | Версии**
- SPT AKI Server version | Версия SPT AKI Server
- SP-EFT-ProfileEditor version | Версия SP-EFT-ProfileEditor

**Describe the bug | Опишите ошибку**
A clear and concise description of what the bug is. | Четкое и краткое описание ошибки.

**Additional context | Дополнительный контекст**
SPT AKI Profile file link | Ссылка на файл профиля SPT AKI

![Screenshot (24)](https://user-images.githubusercontent.com/90663165/133180365-5d4fb62f-83e0-43d5-93a4-fc3f498096a9.png)

**Comment by SkiTles55** [comment]
> 
> ![Screenshot (24)](https://user-images.githubusercontent.com/90663165/133180365-5d4fb62f-83e0-43d5-93a4-fc3f498096a9.png)

1. Issue template is not complete. Learn to read please.
2. Delete PEOptions.json file and try again.
