### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Edbi44** [SkiTles55/SP-EFT-ProfileEditor#9]
**Versions | Версии**
- SPT AKI Server version | 1.5.1
- SP-EFT-ProfileEditor version | 1.8

I can't add or edit anything / Я не могу ничего добавить или отредактировать

![problem](https://user-images.githubusercontent.com/91015101/133927949-398c66e6-af4a-4e36-81aa-91e0497110dc.png)

**Comment by SkiTles55** [comment]
The error means that the profile contains elements added by mods. If you attached a profile file (as indicated in the template) I might be able to fix this problem in the future, but since you ignored it, the only advice is to create a new clean profile, on a server without mods.
